// Generated by CoffeeScript 1.3.3
(function() {
  var Client, Server, express, io, net;

  express = require("express");

  net = require("net");

  io = require("socket.io");

  express = express.createServer();

  io = io.listen(express);

  Client = (function() {

    function Client(socket) {
      var _this = this;
      this.name = socket.remoteAddress + ":" + socket.remotePort;
      io.sockets.emit("client", this.name);
      socket.on("data", function(data) {
        try {
          return io.sockets.emit("acceleration", {
            name: _this.name,
            vector: [data.readFloatLE(0), data.readFloatLE(4), data.readFloatLE(8)]
          });
        } catch (exception) {
          return console.log("Can't understand client. " + exception + ".");
        }
      });
    }

    return Client;

  })();

  Server = (function() {

    function Server(port) {
      var tcp_server,
        _this = this;
      this.clients = [];
      tcp_server = net.createServer(function(socket) {
        return _this.clients.push(new Client(socket));
      });
      tcp_server.listen(port || 5000);
    }

    return Server;

  })();

  new Server;

  express.get("/", function(req, res) {
    return res.sendfile("index.html");
  });

  express.get("/frontend.js", function(req, res) {
    return res.sendfile("frontend.js");
  });

  express.listen(3000);

}).call(this);
